name: Terraform CI/CD

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Select the environment to deploy to'
                required: true
                default: 'dev'
                type: choice
                options:
                    - dev
                    - staging
                    - prod

jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Show selected values
              run: |
                echo "Selected environment: ${{ github.event.inputs.environment }}"
                echo "GitHub event name: ${{ github.event_name }}"
                echo "GitHub ref: ${{ github.ref_name }}"
                echo "GitHub SHA: ${{ github.sha }}"

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v4

            - name: Terraform Init
              run: terraform init
              working-directory: ./terraform

            - name: Terraform Plan
              run: terraform plan -var="environment=${{ github.event.inputs.environment }}" -out=tfplan
              working-directory: ./terraform

            - name: Terraform Apply
              if: github.event_name == 'workflow_dispatch'
              run: terraform apply -auto-approve  tfplan
              working-directory: ./terraform